package za.co.wethinkcode.mastermind;

public class Mastermind {
    private String guess = "";
    private final String code;
    private final Player player;

    public Mastermind(CodeGenerator generator, Player player){
        this.code = generator.generateCode();
        this.player = player;
    }

    public Mastermind(){
        this(new CodeGenerator(), new Player());
    }


//    This method is responsible for printing a message to the console at the end of the game,
//    telling the player whether they won or not and displaying the code that was generated by the computer.
    private void endOfGame(boolean playerWon) {
        String outcomeMassage = playerWon ?
                "Congratulations! You are a codebreaker!" : "No more turns left.";
        System.out.println(outcomeMassage);
        System.out.println("The code was: " + this.code);
    }


//    his method is responsible for displaying the results of evaluating a guess made by the player,
//    indicating how many digits were in the correct place and how many were in the code but not in the correct place
    private void printResults(int correctPlace, int notInCorrectPlace ) {
        System.out.println("Number of correct digits in correct place: "
                + correctPlace);
        System.out.println("Number of correct digits not in correct place: "
                + notInCorrectPlace);
    }


//    This method is responsible for evaluating the player's guess by comparing it to the code
//    generated by the computer, and updating counters to keep track of the number of digits in
//    the guess that are in the correct place and the number of digits that are in the code but not in the correct place.
    private void evaluateInput(){
        int digitsInCorrectPlace = 0;
        int digitsNotInCorrectPlace = 0;

        for (int i = 0; i < this.guess.length(); i++)
            if (this.guess.charAt(i) == this.code.charAt(i))
                digitsInCorrectPlace++;
            else if (this.guess.indexOf(this.code.charAt(i)) > -1)
                digitsNotInCorrectPlace++;

        printResults(digitsInCorrectPlace, digitsNotInCorrectPlace);
    }

//     this method runs the Mastermind game logic by getting the player's guess, evaluating the guess,
//     and determining the outcome of the game based on whether the player won or lost.
//     It also keeps track of the number of turns the player has remaining and displays the appropriate messages to the console

    public void runGame(){
        String firstMassage = "4-digit Code has been set. Digits in range 1 to 8."
                + " You have 12 turns to break it.";
        System.out.println(firstMassage);
        while (this.player.stillHasTurns()) {
            this.guess = this.player.getGuess();
            if (this.player.wantsToQuit())
                break;

            evaluateInput();
            if (this.player.isCorrect(this.guess,this.code) )
                break;

            this.player.lostTurn();
            if (this.player.stillHasTurns())
                System.out.println("Turns left: " + this.player.getTurns());
        }
        if (!player.wantsToQuit())
            endOfGame(this.player.isCorrect(this.guess, this.code));
    }

    public static void main(String[] args){
        Mastermind game = new Mastermind();
        game.runGame();
    }
}
